CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  role VARCHAR(20) NOT NULL CHECK (role IN ('talento', 'empresa')),
  password_hash VARCHAR(255) NOT NULL,
  supabase_user_id UUID UNIQUE,
  accepted_terms_at TIMESTAMPTZ,
  accepted_privacy_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TABLE talent_profiles (
  user_id BIGINT PRIMARY KEY,
  full_name VARCHAR(200),
  headline VARCHAR(200),
  location VARCHAR(200),
  phone VARCHAR(50),
  university VARCHAR(200),
  degree VARCHAR(200),
  grad_year INT,
  gpa NUMERIC(4, 2),
  career_interests TEXT[],
  linkedin VARCHAR(300),
  github VARCHAR(300),
  portfolio VARCHAR(300),
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  CONSTRAINT fk_talent_profiles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE company_profiles (
  user_id BIGINT PRIMARY KEY,
  company_name VARCHAR(200),
  company_size VARCHAR(50),
  industry VARCHAR(200),
  website VARCHAR(300),
  description VARCHAR(2000),
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  CONSTRAINT fk_company_profiles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE cvs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  title VARCHAR(200) NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  CONSTRAINT fk_cvs_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_cvs_user_id ON cvs (user_id);

CREATE TABLE ai_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  kind VARCHAR(20) NOT NULL CHECK (kind IN ('general', 'interview')),
  title VARCHAR(200) NOT NULL,
  model VARCHAR(100) NOT NULL,
  interview_role VARCHAR(200),
  interview_type VARCHAR(20) CHECK (interview_type IN ('técnica', 'rrhh', 'mixta')),
  interview_difficulty VARCHAR(20) CHECK (interview_difficulty IN ('junior', 'mid', 'senior')),
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  CONSTRAINT fk_ai_sessions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_ai_sessions_user_kind ON ai_sessions (user_id, kind);

CREATE TABLE ai_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT NOT NULL,
  role VARCHAR(20) NOT NULL CHECK (role IN ('system', 'user', 'assistant')),
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  CONSTRAINT fk_ai_messages_session FOREIGN KEY (session_id) REFERENCES ai_sessions (id) ON DELETE CASCADE
);

CREATE INDEX idx_ai_messages_session_id ON ai_messages (session_id);

CREATE TABLE jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_user_id BIGINT NOT NULL,
  title VARCHAR(200) NOT NULL,
  description TEXT NOT NULL,
  location VARCHAR(200),
  employment_type VARCHAR(30) NOT NULL DEFAULT 'full_time' CHECK (employment_type IN ('full_time', 'part_time', 'contract', 'internship')),
  seniority VARCHAR(30) NOT NULL DEFAULT 'junior' CHECK (seniority IN ('junior', 'mid', 'senior')),
  salary_min INT,
  salary_max INT,
  status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'paused')),
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  CONSTRAINT fk_jobs_company FOREIGN KEY (company_user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_jobs_company_user_id ON jobs (company_user_id);
CREATE INDEX idx_jobs_status_created_at ON jobs (status, created_at DESC);

CREATE TABLE job_applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id BIGINT NOT NULL,
  talent_user_id BIGINT NOT NULL,
  cover_letter TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'submitted' CHECK (status IN ('submitted', 'withdrawn', 'rejected', 'accepted')),
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  CONSTRAINT fk_job_applications_job FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE CASCADE,
  CONSTRAINT fk_job_applications_talent FOREIGN KEY (talent_user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT uq_job_applications UNIQUE (job_id, talent_user_id)
);

CREATE INDEX idx_job_applications_job_id ON job_applications (job_id);
CREATE INDEX idx_job_applications_talent_user_id ON job_applications (talent_user_id);
