CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  role VARCHAR(20) NOT NULL CHECK (role IN ('talento', 'empresa')),
  password_hash VARCHAR(255) NOT NULL,
  supabase_user_id UUID UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TABLE talent_profiles (
  user_id BIGINT PRIMARY KEY,
  full_name VARCHAR(200),
  headline VARCHAR(200),
  location VARCHAR(200),
  phone VARCHAR(50),
  linkedin VARCHAR(300),
  github VARCHAR(300),
  portfolio VARCHAR(300),
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  CONSTRAINT fk_talent_profiles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE company_profiles (
  user_id BIGINT PRIMARY KEY,
  company_name VARCHAR(200),
  industry VARCHAR(200),
  website VARCHAR(300),
  description VARCHAR(2000),
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  CONSTRAINT fk_company_profiles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE cvs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  title VARCHAR(200) NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  CONSTRAINT fk_cvs_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_cvs_user_id ON cvs (user_id);

CREATE TABLE ai_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  kind VARCHAR(20) NOT NULL CHECK (kind IN ('general', 'interview')),
  title VARCHAR(200) NOT NULL,
  model VARCHAR(100) NOT NULL,
  interview_role VARCHAR(200),
  interview_type VARCHAR(20) CHECK (interview_type IN ('técnica', 'rrhh', 'mixta')),
  interview_difficulty VARCHAR(20) CHECK (interview_difficulty IN ('junior', 'mid', 'senior')),
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  CONSTRAINT fk_ai_sessions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_ai_sessions_user_kind ON ai_sessions (user_id, kind);

CREATE TABLE ai_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT NOT NULL,
  role VARCHAR(20) NOT NULL CHECK (role IN ('system', 'user', 'assistant')),
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  CONSTRAINT fk_ai_messages_session FOREIGN KEY (session_id) REFERENCES ai_sessions (id) ON DELETE CASCADE
);

CREATE INDEX idx_ai_messages_session_id ON ai_messages (session_id);
