// ╔══════════════════════════════════════════════════════════════════════╗
// ║ Archivo:     postgreSQL.ts                                           ║
// ║ Módulo:      backend/src/shared/db                                   ║
// ║ Descripción: Adaptador de base de datos PostgreSQL/Supabase.         ║
// ║ Creado:      20-05-2026                                              ║
// ╚══════════════════════════════════════════════════════════════════════╝

import type { Env } from "../../config/env";
import postgres from "postgres";

export type Db = {
  sql: any;
  execute<T = any>(sqlText: string, binds?: Record<string, any>): Promise<{ rows: T[] }>;
  queryOne<T = any>(sqlText: string, binds?: Record<string, any>): Promise<T | null>;
  queryMany<T = any>(sqlText: string, binds?: Record<string, any>): Promise<T[]>;
};

function compileNamedBinds(sqlText: string, binds: Record<string, any>) {
  const values: any[] = [];
  const nameToIndex = new Map<string, number>();
  const normalizedBinds = binds ?? {};

  const text = sqlText.replace(
    /(?<!:):([a-zA-Z_][a-zA-Z0-9_]*)/g,
    (_m, name: string) => {
      if (!(name in normalizedBinds)) {
        throw new Error(`Falta bind requerido :${name}`);
      }
      const existing = nameToIndex.get(name);
      if (existing) return `$${existing}`;
      const idx = values.length + 1;
      nameToIndex.set(name, idx);
      values.push(normalizedBinds[name]);
      return `$${idx}`;
    },
  );

  return { text, values };
}

/**
 * Inicializa el cliente PostgreSQL (Supabase) y expone helpers para ejecutar queries.
 *
 * Variables:
 * - DATABASE_URL
 * - DB_TEST_ON_STARTUP=true ejecuta `SELECT 1` al iniciar.
 */
export async function createDb(env: Env): Promise<Db> {
  if (!env.databaseUrl) throw new Error("Falta DATABASE_URL.");

  const sql = postgres(env.databaseUrl);

  if (env.dbTestOnStartup) {
    try {
      await sql`SELECT 1 AS value`;
      process.stdout.write("Postgres: conexión verificada correctamente.\n");
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      process.stderr.write(`Postgres: fallo en prueba de conexión. Detalle: ${msg}\n`);
      throw e;
    }
  }

  try {
    await sql.unsafe(`ALTER TABLE users ADD COLUMN IF NOT EXISTS accepted_terms_at TIMESTAMPTZ`, []);
    await sql.unsafe(`ALTER TABLE users ADD COLUMN IF NOT EXISTS accepted_privacy_at TIMESTAMPTZ`, []);
  } catch { }

  try {
    await sql.unsafe(`ALTER TABLE talent_profiles ADD COLUMN IF NOT EXISTS university VARCHAR(200)`, []);
    await sql.unsafe(`ALTER TABLE talent_profiles ADD COLUMN IF NOT EXISTS degree VARCHAR(200)`, []);
    await sql.unsafe(`ALTER TABLE talent_profiles ADD COLUMN IF NOT EXISTS grad_year INT`, []);
    await sql.unsafe(`ALTER TABLE talent_profiles ADD COLUMN IF NOT EXISTS gpa NUMERIC(4, 2)`, []);
    await sql.unsafe(`ALTER TABLE talent_profiles ADD COLUMN IF NOT EXISTS career_interests TEXT[]`, []);
  } catch { }

  try {
    await sql.unsafe(`ALTER TABLE company_profiles ADD COLUMN IF NOT EXISTS company_size VARCHAR(50)`, []);
  } catch { }

  try {
    await sql.unsafe(`CREATE TABLE IF NOT EXISTS jobs (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_user_id BIGINT NOT NULL,
      title VARCHAR(200) NOT NULL,
      description TEXT NOT NULL,
      location VARCHAR(200),
      employment_type VARCHAR(30) NOT NULL DEFAULT 'full_time' CHECK (employment_type IN ('full_time', 'part_time', 'contract', 'internship')),
      seniority VARCHAR(30) NOT NULL DEFAULT 'junior' CHECK (seniority IN ('junior', 'mid', 'senior')),
      salary_min INT,
      salary_max INT,
      status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'paused')),
      created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
      updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
      CONSTRAINT fk_jobs_company FOREIGN KEY (company_user_id) REFERENCES users (id) ON DELETE CASCADE
    )`, []);

    await sql.unsafe(`CREATE INDEX IF NOT EXISTS idx_jobs_company_user_id ON jobs (company_user_id)`, []);
    await sql.unsafe(`CREATE INDEX IF NOT EXISTS idx_jobs_status_created_at ON jobs (status, created_at DESC)`, []);

    await sql.unsafe(`CREATE TABLE IF NOT EXISTS job_applications (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      job_id BIGINT NOT NULL,
      talent_user_id BIGINT NOT NULL,
      cover_letter TEXT,
      status VARCHAR(20) NOT NULL DEFAULT 'submitted' CHECK (status IN ('submitted', 'withdrawn', 'rejected', 'accepted')),
      created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
      updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
      CONSTRAINT fk_job_applications_job FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE CASCADE,
      CONSTRAINT fk_job_applications_talent FOREIGN KEY (talent_user_id) REFERENCES users (id) ON DELETE CASCADE,
      CONSTRAINT uq_job_applications UNIQUE (job_id, talent_user_id)
    )`, []);

    await sql.unsafe(`CREATE INDEX IF NOT EXISTS idx_job_applications_job_id ON job_applications (job_id)`, []);
    await sql.unsafe(`CREATE INDEX IF NOT EXISTS idx_job_applications_talent_user_id ON job_applications (talent_user_id)`, []);
  } catch { }

  async function execute<T = any>(sqlText: string, binds: Record<string, any> = {}) {
    const { text, values } = compileNamedBinds(sqlText, binds);
    const rows = (await sql.unsafe(text, values)) as T[];
    return { rows };
  }

  async function queryMany<T = any>(sqlText: string, binds: Record<string, any> = {}) {
    const res = await execute<T>(sqlText, binds);
    return res.rows;
  }

  async function queryOne<T = any>(sqlText: string, binds: Record<string, any> = {}) {
    const rows = await queryMany<T>(sqlText, binds);
    return rows[0] ?? null;
  }

  return { sql, execute, queryOne, queryMany };
}

/**
 * Cierra el cliente PostgreSQL.
 */
export async function closeDb(db: Db) {
  await db.sql.end({ timeout: 10 });
}
