// ╔══════════════════════════════════════════════════════════════════════╗
// ║ Archivo:     postgreSQL.ts                                           ║
// ║ Módulo:      backend/src/shared/db                                   ║
// ║ Descripción: Adaptador de base de datos PostgreSQL/Supabase.         ║
// ║ Creado:      20-05-2026                                              ║
// ╚══════════════════════════════════════════════════════════════════════╝

import type { Env } from "../../config/env";
import dns from "node:dns";
import postgres from "postgres";

// ── Forzar IPv4 en la resolución DNS ────────────────────────────────────
dns.setDefaultResultOrder("ipv4first");

export type Db = {
  sql: any;
  execute<T = any>(sqlText: string, binds?: Record<string, any>): Promise<{ rows: T[] }>;
  queryOne<T = any>(sqlText: string, binds?: Record<string, any>): Promise<T | null>;
  queryMany<T = any>(sqlText: string, binds?: Record<string, any>): Promise<T[]>;
};

function resolveSslMode(databaseUrl: string) {
  try {
    const url = new URL(databaseUrl);
    const host = url.hostname.trim().toLowerCase();
    if (["db", "localhost", "127.0.0.1"].includes(host)) return false;
  } catch {}
  return "require" as const;
}

function compileNamedBinds(sqlText: string, binds: Record<string, any>) {
  const values: any[] = [];
  const nameToIndex = new Map<string, number>();
  const normalizedBinds = binds ?? {};

  const text = sqlText.replace(
    /(?<!:):([a-zA-Z_][a-zA-Z0-9_]*)/g,
    (_m, name: string) => {
      if (!(name in normalizedBinds)) {
        throw new Error(`Falta bind requerido :${name}`);
      }
      const existing = nameToIndex.get(name);
      if (existing) return `$${existing}`;
      const idx = values.length + 1;
      nameToIndex.set(name, idx);
      values.push(normalizedBinds[name]);
      return `$${idx}`;
    },
  );

  return { text, values };
}

// ── Schema consolidado en un único round-trip ───────────────────────────
// Todos los CREATE/ALTER/INDEX se ejecutan en un solo bloque DO $$ ... $$
// para evitar ~50 round-trips seriales contra Supabase en cada arranque.
const SCHEMA_SQL = `
DO $$ BEGIN

  -- ── Función updated_at ──────────────────────────────────────────────
  CREATE OR REPLACE FUNCTION set_updated_at()
  RETURNS TRIGGER AS $fn$
  BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
  END;
  $fn$ LANGUAGE plpgsql;

  -- ── users ────────────────────────────────────────────────────────────
  CREATE TABLE IF NOT EXISTS users (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email               VARCHAR(255) NOT NULL UNIQUE,
    role                VARCHAR(20)  NOT NULL CHECK (role IN ('talento', 'empresa')),
    password_hash       VARCHAR(255) NOT NULL,
    supabase_user_id    UUID UNIQUE,
    accepted_terms_at   TIMESTAMPTZ,
    accepted_privacy_at TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  ALTER TABLE users ADD COLUMN IF NOT EXISTS accepted_terms_at   TIMESTAMPTZ;
  ALTER TABLE users ADD COLUMN IF NOT EXISTS accepted_privacy_at TIMESTAMPTZ;

  DROP TRIGGER IF EXISTS trg_users_set_updated_at ON users;
  CREATE TRIGGER trg_users_set_updated_at
    BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION set_updated_at();

  -- ── talent_profiles ──────────────────────────────────────────────────
  CREATE TABLE IF NOT EXISTS talent_profiles (
    user_id          BIGINT PRIMARY KEY,
    full_name        VARCHAR(200),
    headline         VARCHAR(200),
    location         VARCHAR(200),
    phone            VARCHAR(50),
    company_user_id  BIGINT,
    university       VARCHAR(200),
    degree           VARCHAR(200),
    grad_year        INT  CHECK (grad_year IS NULL OR (grad_year >= 1900 AND grad_year <= 2100)),
    gpa              NUMERIC(4,2) CHECK (gpa IS NULL OR (gpa >= 0 AND gpa <= 5)),
    career_interests TEXT[],
    linkedin         VARCHAR(300),
    github           VARCHAR(300),
    portfolio        VARCHAR(300),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_talent_profiles_user    FOREIGN KEY (user_id)         REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_talent_profiles_company FOREIGN KEY (company_user_id) REFERENCES users (id) ON DELETE SET NULL
  );

  ALTER TABLE talent_profiles ADD COLUMN IF NOT EXISTS university       VARCHAR(200);
  ALTER TABLE talent_profiles ADD COLUMN IF NOT EXISTS degree           VARCHAR(200);
  ALTER TABLE talent_profiles ADD COLUMN IF NOT EXISTS grad_year        INT;
  ALTER TABLE talent_profiles ADD COLUMN IF NOT EXISTS gpa              NUMERIC(4,2);
  ALTER TABLE talent_profiles ADD COLUMN IF NOT EXISTS career_interests TEXT[];
  ALTER TABLE talent_profiles ADD COLUMN IF NOT EXISTS company_user_id  BIGINT;

  CREATE INDEX IF NOT EXISTS idx_talent_profiles_company_user_id ON talent_profiles (company_user_id);

  DROP TRIGGER IF EXISTS trg_talent_profiles_set_updated_at ON talent_profiles;
  CREATE TRIGGER trg_talent_profiles_set_updated_at
    BEFORE UPDATE ON talent_profiles FOR EACH ROW EXECUTE FUNCTION set_updated_at();

  -- ── company_profiles ─────────────────────────────────────────────────
  CREATE TABLE IF NOT EXISTS company_profiles (
    user_id                       BIGINT PRIMARY KEY,
    company_name                  VARCHAR(200),
    legal_name                    VARCHAR(200),
    tax_id                        VARCHAR(120),
    company_size                  VARCHAR(50),
    industry                      VARCHAR(200),
    activity_sector               VARCHAR(200),
    location                      VARCHAR(200),
    address                       VARCHAR(300),
    contact_email                 VARCHAR(320),
    website                       VARCHAR(300),
    description                   VARCHAR(2000),
    verification_status           VARCHAR(20) NOT NULL DEFAULT 'pending'
      CHECK (verification_status IN ('pending','verified')),
    verification_acknowledged_at  TIMESTAMPTZ,
    accepted_company_terms_at     TIMESTAMPTZ,
    created_at                    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_company_profiles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
  );

  ALTER TABLE company_profiles ADD COLUMN IF NOT EXISTS company_size                 VARCHAR(50);
  ALTER TABLE company_profiles ADD COLUMN IF NOT EXISTS legal_name                   VARCHAR(200);
  ALTER TABLE company_profiles ADD COLUMN IF NOT EXISTS tax_id                       VARCHAR(120);
  ALTER TABLE company_profiles ADD COLUMN IF NOT EXISTS industry                     VARCHAR(200);
  ALTER TABLE company_profiles ADD COLUMN IF NOT EXISTS activity_sector              VARCHAR(200);
  ALTER TABLE company_profiles ADD COLUMN IF NOT EXISTS location                     VARCHAR(200);
  ALTER TABLE company_profiles ADD COLUMN IF NOT EXISTS address                      VARCHAR(300);
  ALTER TABLE company_profiles ADD COLUMN IF NOT EXISTS contact_email                VARCHAR(320);
  ALTER TABLE company_profiles ADD COLUMN IF NOT EXISTS website                      VARCHAR(300);
  ALTER TABLE company_profiles ADD COLUMN IF NOT EXISTS description                  VARCHAR(2000);
  ALTER TABLE company_profiles ADD COLUMN IF NOT EXISTS verification_status          VARCHAR(20);
  ALTER TABLE company_profiles ADD COLUMN IF NOT EXISTS verification_acknowledged_at TIMESTAMPTZ;
  ALTER TABLE company_profiles ADD COLUMN IF NOT EXISTS accepted_company_terms_at    TIMESTAMPTZ;
  ALTER TABLE company_profiles ALTER COLUMN verification_status SET DEFAULT 'pending';
  UPDATE company_profiles SET verification_status = 'pending' WHERE verification_status IS NULL;

  DROP TRIGGER IF EXISTS trg_company_profiles_set_updated_at ON company_profiles;
  CREATE TRIGGER trg_company_profiles_set_updated_at
    BEFORE UPDATE ON company_profiles FOR EACH ROW EXECUTE FUNCTION set_updated_at();

  -- ── cvs ──────────────────────────────────────────────────────────────
  CREATE TABLE IF NOT EXISTS cvs (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    title      VARCHAR(200) NOT NULL,
    content    TEXT         NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_cvs_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
  );

  CREATE INDEX IF NOT EXISTS idx_cvs_user_id ON cvs (user_id);

  DROP TRIGGER IF EXISTS trg_cvs_set_updated_at ON cvs;
  CREATE TRIGGER trg_cvs_set_updated_at
    BEFORE UPDATE ON cvs FOR EACH ROW EXECUTE FUNCTION set_updated_at();

  -- ── ai_sessions ──────────────────────────────────────────────────────
  CREATE TABLE IF NOT EXISTS ai_sessions (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT       NOT NULL,
    kind                 VARCHAR(20)  NOT NULL CHECK (kind IN ('general','interview')),
    title                VARCHAR(200) NOT NULL,
    model                VARCHAR(100) NOT NULL,
    interview_role       VARCHAR(200),
    interview_type       VARCHAR(20)  CHECK (interview_type IN ('técnica','rrhh','mixta')),
    interview_difficulty VARCHAR(20)  CHECK (interview_difficulty IN ('junior','mid','senior')),
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_ai_sessions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
  );

  CREATE INDEX IF NOT EXISTS idx_ai_sessions_user_kind ON ai_sessions (user_id, kind);

  DROP TRIGGER IF EXISTS trg_ai_sessions_set_updated_at ON ai_sessions;
  CREATE TRIGGER trg_ai_sessions_set_updated_at
    BEFORE UPDATE ON ai_sessions FOR EACH ROW EXECUTE FUNCTION set_updated_at();

  -- ── ai_messages ──────────────────────────────────────────────────────
  CREATE TABLE IF NOT EXISTS ai_messages (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT      NOT NULL,
    role       VARCHAR(20) NOT NULL CHECK (role IN ('system','user','assistant')),
    content    TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_ai_messages_session FOREIGN KEY (session_id) REFERENCES ai_sessions (id) ON DELETE CASCADE
  );

  CREATE INDEX IF NOT EXISTS idx_ai_messages_session_id ON ai_messages (session_id);

  -- ── jobs ─────────────────────────────────────────────────────────────
  CREATE TABLE IF NOT EXISTS jobs (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_user_id      BIGINT       NOT NULL,
    title                VARCHAR(200) NOT NULL,
    description          TEXT         NOT NULL,
    requirements         TEXT,
    benefits             TEXT,
    location             VARCHAR(200),
    employment_type      VARCHAR(30)  NOT NULL DEFAULT 'full_time'
      CHECK (employment_type IN ('full_time','part_time','contract','internship')),
    seniority            VARCHAR(30)  NOT NULL DEFAULT 'junior'
      CHECK (seniority IN ('junior','mid','senior')),
    salary_min           INT,
    salary_max           INT,
    application_deadline TIMESTAMPTZ,
    status               VARCHAR(20)  NOT NULL DEFAULT 'active'
      CHECK (status IN ('active','paused','closed')),
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_jobs_company      FOREIGN KEY (company_user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT chk_jobs_salary_range CHECK (salary_min IS NULL OR salary_max IS NULL OR salary_min <= salary_max)
  );

  ALTER TABLE jobs ADD COLUMN IF NOT EXISTS requirements         TEXT;
  ALTER TABLE jobs ADD COLUMN IF NOT EXISTS benefits             TEXT;
  ALTER TABLE jobs ADD COLUMN IF NOT EXISTS application_deadline TIMESTAMPTZ;

  CREATE INDEX IF NOT EXISTS idx_jobs_company_user_id     ON jobs (company_user_id);
  CREATE INDEX IF NOT EXISTS idx_jobs_status_created_at   ON jobs (status, created_at DESC);

  -- ── job_applications ─────────────────────────────────────────────────
  CREATE TABLE IF NOT EXISTS job_applications (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id          BIGINT      NOT NULL,
    talent_user_id  BIGINT      NOT NULL,
    cover_letter    TEXT,
    status          VARCHAR(20) NOT NULL DEFAULT 'submitted'
      CHECK (status IN ('submitted','withdrawn','rejected','accepted')),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_job_applications_job    FOREIGN KEY (job_id)         REFERENCES jobs  (id) ON DELETE CASCADE,
    CONSTRAINT fk_job_applications_talent FOREIGN KEY (talent_user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_job_applications        UNIQUE (job_id, talent_user_id)
  );

  CREATE INDEX IF NOT EXISTS idx_job_applications_job_id        ON job_applications (job_id);
  CREATE INDEX IF NOT EXISTS idx_job_applications_talent_user_id ON job_applications (talent_user_id);

  -- ── application_conversations ────────────────────────────────────────
  CREATE TABLE IF NOT EXISTS application_conversations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id  BIGINT NOT NULL UNIQUE,
    company_user_id BIGINT NOT NULL,
    talent_user_id  BIGINT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_application_conversations_application FOREIGN KEY (application_id)  REFERENCES job_applications (id) ON DELETE CASCADE,
    CONSTRAINT fk_application_conversations_company     FOREIGN KEY (company_user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_application_conversations_talent      FOREIGN KEY (talent_user_id)  REFERENCES users (id) ON DELETE CASCADE
  );

  CREATE INDEX IF NOT EXISTS idx_application_conversations_company ON application_conversations (company_user_id, updated_at DESC);
  CREATE INDEX IF NOT EXISTS idx_application_conversations_talent  ON application_conversations (talent_user_id,  updated_at DESC);

  -- ── conversation_messages ────────────────────────────────────────────
  CREATE TABLE IF NOT EXISTS conversation_messages (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id       BIGINT       NOT NULL,
    sender_user_id        BIGINT       NOT NULL,
    body                  TEXT         NOT NULL,
    attachment_name       VARCHAR(255),
    attachment_url        VARCHAR(500),
    scheduled_interview_at TIMESTAMPTZ,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_conversation_messages_conversation FOREIGN KEY (conversation_id) REFERENCES application_conversations (id) ON DELETE CASCADE,
    CONSTRAINT fk_conversation_messages_sender       FOREIGN KEY (sender_user_id)  REFERENCES users (id) ON DELETE CASCADE
  );

  CREATE INDEX IF NOT EXISTS idx_conversation_messages_conversation ON conversation_messages (conversation_id, created_at ASC);

  -- ── conversation_files ───────────────────────────────────────────────
  CREATE TABLE IF NOT EXISTS conversation_files (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT       NOT NULL,
    uploader_user_id BIGINT      NOT NULL,
    file_name       VARCHAR(255) NOT NULL,
    mime_type       VARCHAR(120) NOT NULL DEFAULT 'application/octet-stream',
    size_bytes      INT          NOT NULL,
    data            BYTEA        NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_conversation_files_conversation FOREIGN KEY (conversation_id)  REFERENCES application_conversations (id) ON DELETE CASCADE,
    CONSTRAINT fk_conversation_files_uploader     FOREIGN KEY (uploader_user_id) REFERENCES users (id) ON DELETE CASCADE
  );

  CREATE INDEX IF NOT EXISTS idx_conversation_files_conversation_id ON conversation_files (conversation_id, created_at DESC);

  -- ── career_interest_options ──────────────────────────────────────────
  CREATE TABLE IF NOT EXISTS career_interest_options (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug       VARCHAR(120) NOT NULL UNIQUE,
    label      VARCHAR(200) NOT NULL,
    category   VARCHAR(120),
    sort_order INT          NOT NULL DEFAULT 0,
    is_active  BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW()
  );

  CREATE INDEX IF NOT EXISTS idx_career_interest_options_active_sort ON career_interest_options (is_active, sort_order);

  INSERT INTO career_interest_options (slug, label, category, sort_order) VALUES
    ('desarrollo-frontend', 'Desarrollo Frontend',  'tech',    10),
    ('analisis-de-datos',   'Análisis de Datos',    'tech',    20),
    ('ciberseguridad',      'Ciberseguridad',        'tech',    30),
    ('diseno-ux-ui',        'Diseño UX/UI',          'product', 40),
    ('gestion-de-producto', 'Gestión de Producto',   'product', 50),
    ('marketing-digital',   'Marketing Digital',     'growth',  60),
    ('machine-learning',    'Machine Learning',      'tech',    70),
    ('arquitectura-cloud',  'Arquitectura Cloud',    'tech',    80)
  ON CONFLICT (slug) DO NOTHING;

END $$;
`;

/**
 * Inicializa el cliente PostgreSQL (Supabase) y expone helpers para ejecutar queries.
 * El schema se aplica en un único round-trip para minimizar latencia de red.
 */
export async function createDb(env: Env): Promise<Db> {
  if (!env.databaseUrl) throw new Error("Falta DATABASE_URL.");

  const sql = postgres(env.databaseUrl, { ssl: resolveSslMode(env.databaseUrl) });

  if (env.dbTestOnStartup) {
    try {
      await sql`SELECT 1 AS value`;
      process.stdout.write("Postgres: conexión verificada correctamente.\n");
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      process.stderr.write(`Postgres: fallo en prueba de conexión. Detalle: ${msg}\n`);
      throw e;
    }
  }

  // Un único round-trip para todo el schema
  try {
    await sql.unsafe(SCHEMA_SQL, []);
    process.stdout.write("Postgres: schema sincronizado.\n");
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    process.stderr.write(`Postgres: error al sincronizar schema. Detalle: ${msg}\n`);
    throw e;
  }

  async function execute<T = any>(sqlText: string, binds: Record<string, any> = {}) {
    const { text, values } = compileNamedBinds(sqlText, binds);
    const rows = (await sql.unsafe(text, values)) as T[];
    return { rows };
  }

  async function queryMany<T = any>(sqlText: string, binds: Record<string, any> = {}) {
    const res = await execute<T>(sqlText, binds);
    return res.rows;
  }

  async function queryOne<T = any>(sqlText: string, binds: Record<string, any> = {}) {
    const rows = await queryMany<T>(sqlText, binds);
    return rows[0] ?? null;
  }

  return { sql, execute, queryOne, queryMany };
}

/**
 * Cierra el cliente PostgreSQL.
 */
export async function closeDb(db: Db) {
  await db.sql.end({ timeout: 10 });
}
